port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - name: vless-reality-user1
    type: vless
    server: 38.180.216.5
    port: 443
    uuid: bac796fe-09a1-4630-c174-a2324a11ca7d
    network: tcp
    tls: true
    servername: github.com
    reality-opts:
      public-key: GLipc4FYcLA4qxV1WdOsTVH22iyQQUz6VkNXTfPkJFk
      short-id: ""
    udp: true

proxy-groups:
  - name: 🚀 Proxy
    type: select
    proxies:
      - vless-reality-user1
      - DIRECT

rules:
  # Apple goes DIRECT
  - DOMAIN-SUFFIX,apple.com,DIRECT
  - DOMAIN-SUFFIX,icloud.com,DIRECT
  - DOMAIN-SUFFIX,itunes.apple.com,DIRECT
  - DOMAIN-SUFFIX,me.com,DIRECT
  - DOMAIN-SUFFIX,mac.com,DIRECT

  # Google, Telegram, Netflix through Proxy
  - DOMAIN-SUFFIX,google.com,🚀 Proxy
  - DOMAIN-SUFFIX,github.com,🚀 Proxy
  - DOMAIN-SUFFIX,telegram.org,🚀 Proxy
  - DOMAIN-SUFFIX,netflix.com,🚀 Proxy
  - DOMAIN-SUFFIX,steamcommunity.com,🚀 Proxy

  # Local LAN
  - GEOIP,CN,DIRECT
  - MATCH,🚀 Proxy

dns:
  enable: true
  listen: 0.0.0.0:1053
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
